topfreegames/podium

util/expire.go
util/expire_test.go

If expire was equal to 0, podium was returning a non intuitive error (redis: error nil). This commit fixes it.

Expire should also return errors when expiration is equal to 0 seconds.

---

api/app_test.go
api/leaderboard.go
api/leaderboard_test.go
docs/API.md
leaderboard/leaderboard.go
leaderboard/leaderboard_test.go

This new query parameter deals with the case when the player is not
in the ranking, if the flag is enabled then the last players in the
ranking are returned instead of returning 404.
Default behavior does not change, should not break compatibility.
@cscatolini could you take a look?

Added a new query parameter for GetAroundMe

---

api/app.go
api/app_test.go
api/helpers.go
api/helpers_test.go
api/leaderboard.go
api/leaderboard_test.go
api/middleware.go
cmd/start.go
cmd/worker.go
glide.lock
glide.yaml
leaderboard/leaderboard.go
leaderboard/leaderboard_test.go
log/log.go
testing/extensions.go
testing/logger.go
util/errors.go
util/expire.go
util/expire_test.go
util/redis.go
worker/expiration_worker.go

* New error type: LeaderboardExpiredError. Returns http.StatusBadRequest instead of http.StatusInternalServerError when trying to increment/upsert to an expired leaderboard.
* Changed path to uber's zap library (was getting errors after make setup + make test)

LeaderboardExpiredError

---

api/app.go
api/healthcheck.go
api/healthcheck_test.go
api/helpers_test.go
api/leaderboard.go
api/leaderboard_test.go
bench/helpers.go
bench/leaderboard_test.go
leaderboard/helpers_test.go
leaderboard/leaderboard.go
leaderboard/leaderboard_test.go
worker/expiration_worker_test.go

Now clients of the podium library can instantiate a client without managing Redis themselves. Refactoring for this also brought the opportunity to make the API cleaner: we no longer need to create a leaderboard every time an operation is needed. We use a single leaderboard client that gives us all leaderboard functionality and redis management.

added redis config to leaderboard and refactored leaderboard module

---

Makefile
proto/podium/api/v1/podium.pb.go
prototool.yaml
third-party/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/LICENSE
third-party/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/README.grpc-gateway
third-party/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api/annotations.proto
third-party/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api/http.proto
third-party/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api/httpbody.proto
third-party/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/rpc/code.proto
third-party/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/rpc/error_details.proto
third-party/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/rpc/status.proto

WIP: This PR is to implement some of the remaining TODO items left on the Podium project.

added prototool

---

.github/workflows/go.yml
Makefile

WHY
=======
Podium ci only executes a test step. This PR proposes to add `build_and_push` steps that to each commit successfully tested will push a new image to [podium-dev repository](https://hub.docker.com/r/tfgco/podium-dev) and to each new tag will push a new image to [podium repository](https://hub.docker.com/r/tfgco/podium)
WHAT WAS DONE
=======
* Add build_and_push_dev step to ci
* Add build_and_push step to ci

Add build and push to ci

---

docs/API.md

Documentation currently states that the "get members around member" route with the query parameter  "getLastIfNotFound" set to true treats members not found in the ranking as being in the last position. However, that implies that the member will be included in the returning member list, which is not the case. I have reworded this sentence to reflect better what the implementation does.

Fix error in API docs

---

.github/workflows/go.yml

Ever since the last release #40, we now have a leaderboard module that does not have a docker image, so this PR strips it out

Do not create Leaderboard docker imgs

---

Makefile
bench/helpers.go
build/InitializeRedisClusterDockerfile
build/RedisClusterDockerfile
build/TestAppDockerfile
build/package/initialize_cluster.sh
build/package/redis_cluster.conf
build/package/start_redis.sh
config/test.yaml
deployments/docker-compose.yaml
leaderboard/leaderboard_test.go
leaderboard/testing/config.go
testing/config.go
worker/expiration_worker_test.go

WHY
======
Currently, Podium only has the environment to test Redis standalone. This PR proposes to create a docker-compose file that will create a proper environment to test these new features.
WHAT WAS DONE
======
* Create `docker-compose.yaml`
* Fix tests

Create docker-compose to redis-cluster and fix tests

---

.github/workflows/go.yml
config/default.yaml
config/test.yaml
deployments/docker-compose-model.yaml
leaderboard/go.mod
leaderboard/go.sum
leaderboard/redis/cluster_client.go
leaderboard/redis/cluster_client_test.go
leaderboard/redis/errors.go
leaderboard/redis/redis.go
leaderboard/redis/redis_suite_test.go
leaderboard/redis/standalone_client.go
leaderboard/redis/standalone_client_test.go

WHY
=======
Podium needs to support both Redis standalone and Redis cluster clients. To achieve this goal this PR proposes to create inside leaderboard a package to hold an interface to standardize the way to communicate with Redis. And two implementations `clusterClient` and `standaloneClient`.
WHAT WAS DONE
=======
* Create `leaderboard.Redis` interface to standardize Redis communication across all Podium
* Create `leaderboard.NewStandaloneClient` to instantiate a New Redis standalone client
* Create `leaderboard.NewClusterClient` to instantiate a New Redis Cluster client

Create leaderboard/redis package

---

leaderboard/model/member.go

WHY
======
To hold data structure that will be used across all leaderboard, the PR proposes to create `Member` model.
WHAT WAS DONE
======
* Create `Member` model

Create model member

---

api/leaderboard_test.go

WHY
=======
Tests are broken because golang `time.Now().AddDate(0, -2, 0)` (04/20/2021) plus `previousTime.AddDate(0, 2, 0) is resulting in (05/01/2021) that is a valid expiration time and it is making test broken.
WHAT WAS DONE
=======
* Change test to use `time.Now().AddDate(0, -3, 0)` instead previous `-2`

Fix leaderboard time broken test

---

leaderboard/database/database.go
leaderboard/database/errors.go
leaderboard/database/mock.go
leaderboard/database/redis.go
leaderboard/database/redis/cluster_client.go
leaderboard/database/redis/cluster_client_test.go
leaderboard/database/redis/errors.go
leaderboard/database/redis/mock.go
leaderboard/database/redis/redis.go
leaderboard/database/redis/standalone_client.go
leaderboard/database/redis/standalone_client_test.go
leaderboard/database/redis_test.go
leaderboard/interface.go
leaderboard/service/get_member.go
leaderboard/service/get_member_test.go
leaderboard/service/get_members.go
leaderboard/service/get_members_test.go
leaderboard/service/increment_member_score.go
leaderboard/service/increment_member_score_test.go
leaderboard/service/leadeboard.go
leaderboard/service/members.go
leaderboard/service/set_member_score.go
leaderboard/service/set_member_score_test.go
leaderboard/service/set_members_score.go
leaderboard/service/set_members_score_test.go

WHY
=====
This PR proposes to add `SetMembersScore`, `SetMemberScore` and `IncrementMemberScore` service. Another thing is that the leaderboard had different types of time, so this PR proposes to standardize them.
WHAT WAS DONE
=====
* Standardize TTL type
* Add `SetMembersScore`
* Add `SetMemberScore`
* Add `IncrementMemberScore`

Implement update members services

---

leaderboard/database/redis.go
leaderboard/database/redis/cluster_client.go
leaderboard/database/redis/cluster_client_test.go
leaderboard/database/redis/errors.go
leaderboard/database/redis/mock.go
leaderboard/database/redis/redis.go
leaderboard/database/redis/standalone_client.go
leaderboard/database/redis/standalone_client_test.go

WHY
======
Leaderboard integration tests need some redis commands that was not previous developed as `SMembers` and `Exists`. This PR proposes to implement this commands.
WHAT WAS DONE
======
* Improve error messages
* Implement redis `SMembers`command
* Implement redis `Exists`command

Create redis commands to be used by integration tests

---

leaderboard/service/interface.go
leaderboard/service/service.go

WHY
=====
The interface file standardize how leaderboard will work. This PR proposes to move it from leaderboard package to service that in a near future will avoid dependecy loop between service and leaderboard.
WHAT WAS DONE
=====
* Move interface file from `leaderboard` package to `service`

Fix service file

---

leaderboard/service/errors.go
leaderboard/service/get_top_percentage.go
leaderboard/service/get_top_percentage_test.go

WHY
=====
Integration test show some changes that should be done in leaderboard service. This PR proposes to change `GetTopPercentage` that should return descendent order if no order or invalid order is in parameter.
WHAT WAS DONE
=====
* Change `GetTopPercentage` service

Apply integration tests changes to get_top_percentage service

---

leaderboard/service/get_around_me_test.go
leaderboard/service/get_around_score.go
leaderboard/service/get_around_score_test.go
leaderboard/service/get_members.go
leaderboard/service/get_members_test.go
leaderboard/service/indexes.go
leaderboard/service/members.go
leaderboard/service/set_member_score_test.go
leaderboard/service/set_members_score_test.go

WHY
=======
This PR proposes to attack two points.
The first is the previous index calculation on GetAround routes was done moving the center of the range one down, so the index in the service is calculated with error.
The second is fix the time calculation
The third is that when argument `previousRank` is set as `false` the value should be return as `-1`.
WHAT WAS DONE
=======
* Change index calculation
* Fix time calculation
* Set `PreviousRank` as `-1` as when parameter `previousRank` on `GetAround` functions

Refactor GetAround functions to acord to integration tests

---

Makefile
leaderboard/integration_test.go
leaderboard/service/get_around_me_test.go
leaderboard/service/get_around_score_test.go
leaderboard/service/indexes.go

WHY
========
The changes introduce a problem on `GetAroundMe` and `GetAroundScore`, that return less elements than `pageSize` argument. This PR proposes to fix this problem.
WHAT WAS DONE
========
* Add `compose-up-api` command
* Add test to ensure number of elements on functions `GetAroundMe` and `GetAroundScore`

Fix index calculation

---

.github/workflows/go.yml
config/default.yaml
deployments/docker-compose-model.yaml
leaderboard/database/redis.go
leaderboard/database/redis_expiration.go
leaderboard/database/redis_test.go
worker/expiration_worker.go
worker/expiration_worker_test.go

Now that Podium support both standalone and cluster Redis instances, it is necessary for our CI to check if any change is compliant with both implementations. 
This PR adds a new job in our CI to test the implementation against the cluster to ensure nothing breaks. This new job will run in parallel while the standalone test is running on another job.

Add step to test podium with cluster on CI

---

worker/expiration_worker.go
worker/expiration_worker_test.go

When we put POdium `10.1.1` on prod the worker starts to throw an error on `SREM` without members to exclude. This is happening because currently, the number of members to expire is not checked. This PR proposes to check this and refactor expireMembers on `expiration_worker` to improve code quality.
- Add conditional call to ExpireMembers on expiration_worker

Avoid call SREM without member to exclude on worker

---

.github/workflows/go.yml
Makefile
client/go.mod
client/go.sum

Game teams need to use an old version of protobuf, how it is a dependency inside gomega, this PR proposes to downgrade gomega to be appropriated.
* Downgrade gomega in client from `1.12.0` to `1.11.0`

Downgrade gomega to enable use protobuf1.4.3

---

api/app.go
go.mod
go.sum

The previous version of Podium isn't sending spans to jaeger. This was happening because no interceptors was added to HTTP and GRPC servers. This PR proposes to fix this, but another one appear, what is happenning is that when a request was received by Podium in HTTP server it is creating two spans in jaeger, one related to request in HTTP and another in GRPC. This was happening because we use `grpc-gateway` as backend to HTTP requests, so Podium make a request to `GRPC` server with a propper request. But with the change in Jaeger HTTP server is calling GRPC with context that holds opentracing span info.
* Add HTTP middleware to handle trace
* Add GRPC interceptor to handle trace

Connect spans in GRPC and HTTP requests
